language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: blFJqIt+PsaMBS/7l6hva2+PxinPXgFqrSS8FKEijYi5gl1JaY4vXk3HFdIkmNkHemyC/zjNXWTv6dI3mGZWlKdhg8+3BHKnsJd8J5w/1Dg/X79QQcTYuX57auuXvo+iXY92cXlhkgc3478qYjuE2kHP+wwtjU9FugkTPskiGpY=
